version: '3'
services:
  oj-gateway:
    container_name: oj-gateway
    build:
      context: ./oj-gateway
      dockerfile: Dockerfile
    ports:
      - "8109:8109"
    networks:
      - mynetwork
  oj-user-service:
    container_name: oj-user-service
    build:
      context: ./oj-user-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - mynetwork

  oj-question-service:
    container_name: oj-question-service
    build:
      context: ./oj-question-service
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - mynetwork
  oj-judge-service:
    container_name: oj-judge-service
    build:
      context: ./oj-judge-service
      dockerfile: Dockerfile
    ports:
      - "8105:8105"
    networks:
      - mynetwork
# 网络，不定义的话就是默认网络
networks:
  mynetwork:
