# 公共配置文件
spring:
  application:
    name: oj-question-service
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.224.10:8848
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  redis:
    host: 123.207.158.188
    port: 6379
    database: 1
    # session 配置
  rabbitmq:
    host: 8.140.224.10
    port: 5672
    username: guest
    password: guest
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.207.158.188:3306/oj
    username: oj
    password: Coldplay789
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  httpclient:
    enabled: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
logging:
  level:
    com.example.client.UserFeignClient: DEBUG
    com:
      gxy:
        oj:
          mapper: debug

codesandbox:
  type: "remote"
knife4j:
  enable: true
