# 公共配置文件
server:
  port: 8109
spring:
  application:
    name: oj-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.140.224.10:8848
    gateway:
      routes:
        - id: oj-user-service
          uri: lb://oj-user-service
          predicates:
            - Path=/api/user/**
        - id: oj-question-service
          uri: lb://oj-question-service
          predicates:
            - Path=/api/question/**
  main:
    web-application-type: reactive
logging:
  level:
    gxy:
      oj:
        mapper: debug
knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : swagger2
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - gateway-service


